#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School for the win!" | sudo tee /usr/share/nginx/html/index.html
service nginx start
file="/etc/nginx/sites-available/default"
sudo sed -i '/^\tserver_name localhost;/ a\\n\tlocation \/redirect_me \{\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t\}\n' $file
sudo service nginx restart
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i '/^\tserver_name localhost;/ a\\n\terror_page 404 \/custom_404.html;\n\tlocation \/custom_404.html \{\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t\}\n' $file

n=$(hostname)
file2="/etc/nginx/sites-available/default"
sudo sed -i '/^\tserver_name localhost;/ a\\tadd_header X-Served-By '"$n;" $file2

sudo service nginx restart
