#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get update
sudo apt-get install -y haproxy

echo -e "
frontend localnodes
\tbind *:80
\tmode http
\tdefault_backend nodes
\nbackend nodes
\tmode http
\tbalance roundrobin
\toption forwardfor
\thttp-request set-header X-Forwarded-Port %[dst_port]
\thttp-request add-header X-Forwarded-Proto https if { ssl_fc }
\toption httpchk HEAD / HTTP/1.1\\\r\\\nHost:localhost
\tserver web01 35.185.103.245 check
\tserver web02 35.243.154.87 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
