#!/usr/bin/env bash
#get Apache to run on the container and to return a page containing Hello Holberton when querying the root of it.
sudo apt-get update
sudo apt-get -y install apache2
echo "HttpProtocolOptions Unsafe" >> /etc/apache2/apache2.conf
service apache2 restart
