#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with the below requirements
cp /etc/hosts ~/hostTmp
sed -i "s/^127.*host$/127.0.0.2 localhost/" ~/hostTmp
str="$(grep -F 'facebook.com' ~/hostTmp)"
if [ "$str" ]
then
    sed -i "s/.*facebook.com$/8.8.8.8 facebook.com/" ~/hostTmp
else
    sed -i "1i8.8.8.8 facebook.com" ~/hostTmp
fi
cp -f ~/hostTmp /etc/hosts
