#!/usr/bin/env bash
#nginx must be running as nginx user
#nginx must be listening on all active IPs on port 8080
pkill apache2
file="/etc/nginx/sites-available/default"
conf_file="/etc/nginx/nginx.conf"
sed -i 's/80 default_server/8080 default_server/g' $file
chmod u+rwx $conf_file
sed -i '1i user nginx;' $conf_file
chown nginx:nginx $conf_file
sudo -u nginx service nginx restart
